version: "3.4"

services:
  traefik:
    image: rbekker87/armhf-traefik:1.7.0-rc3
    command: 
      - "--api"
      - "--docker" 
      - "--docker.swarmmode"
      - "--docker.domain=domain.co.za"
      - "--docker.watch"
      - "--logLevel=DEBUG"
      - "--web"
    networks:
      - appnet
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 80:80
      - 8080:8080
    deploy:
      mode: global
      restart_policy:
        condition: on-failure
      placement:
        constraints: [node.role == manager]
    #logging:
      #driver: "json-file"
      #options:
        #max-size: "50k"

networks:
  appnet:
    external: true
